name: First Workflow
on: workflow_dispatch
jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Greeting
        run: echo "Hello World!"
      - name: Run Multiline commands
        run: |
          echo "Line1"
          echo "Line2"
      - name: Print Goodbye
        run: echo "Goodbye!"
        
